version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    env_file:
      - .env
    command: bundle exec rails s -b '0.0.0.0'
    volumes:
      - .:/travel-manager
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data:
